baseURL = "https://hugowebmonetization.netlify.com/"
languageCode = "en-us"
title = "Aaron & Sabine"
theme = "hugo-webmonetization-demo"
canonifyURLs = true
paginate = 10

[params]
  monetization = "$twitter.xrptipbot.com/sabinebertram_"