baseURL = "http://example.org/"
languageCode = "en-us"
title = "Aaron & Sabine"
theme = "hugo-webmonetization-demo"
canonifyURLs = true

[params]
  monetization = "$twitter.xrptipbot.com/sabinebertram_"